<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SezerAiWeb.Application\SezerAiWeb.Application.csproj" />
    <ProjectReference Include="..\SezerAiWeb.Infrastructure\SezerAiWeb.Infrastructure.csproj" />
    <ProjectReference Include="..\SezerAiWeb.Persistence\SezerAiWeb.Persistence.csproj" />
    <ProjectReference Include="..\SezerAiWeb.Domain\SezerAiWeb.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5051df1a-1f6d-4379-9985-b36cff1bd66c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Content\Blog\**\*.md" CopyToPublishDirectory="PreserveNewest" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Npgsql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.PostgreSQL" Version="2.3.0" />
  </ItemGroup>

</Project>
